django_instagram_prototype/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

django_instagram_prototype/django_instagram_prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

class RootView(TemplateView):
    template_name = 'root.html'

urlpatterns = [
    # path('', RootView.as_view(), name='root'), # TemplateView.as_view(template_name='root.html')
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
      urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
      import debug_toolbar
      urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

django_instagram_prototype/instagram/urls.py
from django.urls import path, re_path, register_converter
from . import views
from .converters import YearConverter_2000, MonthConverter, DayConverter

app_name = 'instagram' # URL Reverse에서 namespace역할을 하게 됨

register_converter(YearConverter_2000, 'year_2000')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')
 
urlpatterns = [
       path('new/', views.post_new, name='post_new'),
       path('<int:pk>/edit', views.post_edit, name='post_edit'),
       path('<int:pk>/delete', views.post_delete, name='post_delete'),
       path('', views.post_list, name='post_list'),
       path('<int:pk>/', views.post_detail, name='post_detail'),
       #path('archives/<year_2000:year>/', views.archives_year), # re_path(r"archives/(?P<year>20\d{2})/", views.archives_year)
       path('archive/', views.post_archive, name='post_archive'),
       path('archive/<year_2000:year>/', views.post_archive_year, name='post_archive_year'),
]

django_instagram_prototype/instagram/models.py
from django.db import models
import os
from django.urls import reverse
from django.utils import timezone
from uuid import uuid4
from django.conf import settings
from django.core.validators import MinLengthValidator

def uuid_name_upload_to(instance, filename):
    app_label = instance.__class__._meta.app_label # 앱 별로
    cls_name = instance.__class__.__name__.lower() # 모델 별로
    ymd_path = timezone.now().strftime('%Y/%m/%d') # 업로드하는 년/월/일 별로
    uuid_name = uuid4().hex
    extension = os.path.splitext(filename)[-1].lower() # 확장자 추출
    return '/'.join([
        app_label,
        cls_name,
        ymd_path,
        uuid_name + extension,
    ])


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, 
    related_name='instagram_post_set') # reverse_name을 포기하려면 related_name='+'
    photo = models.ImageField(blank=True, upload_to=uuid_name_upload_to)
    message = models.TextField(validators=[MinLengthValidator(10)])
    tag_set = models.ManyToManyField('Tag', blank=True) # ManyToManyField(to, blank)
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True) # 생성시간
    updated_at = models.DateField(auto_now=True) # 수정시간

    class Meta:
        ordering  = ['-id']
        # unique_together = [( author, photo),]

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

class Comment(models.Model):
    # models.ForeignKey 주석
    # to는 문자열로도 지정 가능 ex> 'instagram.Post'
    # on_delete: Record 삭제 시 Rule
    # on_delete=models.CASCADE: FK로 참조하하는 다른 모델의 Record들도 삭제 ex> 하나의 Post가 삭제되면 거기에 속하는 모든 Comment삭제
    post = models.ForeignKey(Post, on_delete=models.CASCADE, # post_id 필드가 생성(id는 Post Model의 pk), post는 가상의 필드
                                    limit_choices_to={'is_public':True})
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField(Post, blank=True)

    def __str__(self):
        return self.name  

django_instagram_prototype/instagram/forms.py
from django import forms
from flask import message_flashed
from .models import Post
import re

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['photo', 'message', 'tag_set', 'is_public'] # 지정된 필드에 한해서만 유효성 검사를 시행
        # exclude = []

    # def clean_message(self):
    #     message = self.cleaned_data.get('message')
    #     if message:
    #         message = re.sub(r'[a-zA-Z]+', '영어가 한번이상 반복 되었습니다.', message)
    #     return message

django_instagram_prototype/instagram/views.py
import re
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect, render, get_object_or_404 # 템플릿 응답을 위한 shortcut 함수
from .models import Post
from django.views.generic import DetailView, ArchiveIndexView, ListView, YearArchiveView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

# @login_required
# def post_new(request):
#     if request.method =='POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid(): # 유효성 검사 수행
#             post = form.save(commit=False)
#             post.author = request.user # 현재 로그인 유저 Instance
#             post.save()
#             messages.success(request, '포스팅을 저장했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm()
    
#     return render(request, 'instagram/post_form.html', {
#         'form':form,
#         'post':None,
#     })

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅을 저장했습니다.')
        return super().form_valid(form)

post_new = PostCreateView.as_view()

# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)

#     # 작성자 check
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정할 수 있습니다.')
#         return redirect(post)

#     if request.method =='POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save(commit=True) # DB에 모델 객체 저장
#             messages.success(request, '포스팅을 수정했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
    
#     return render(request, 'instagram/post_form.html', {
#     'form':form,
#     'post':post,
#     })

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정했습니다.')
        return super().form_valid(form)

post_edit = PostUpdateView.as_view()

# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)

#     if post.author != request.user:
#         messages.error(request, '작성자만 삭제할 수 있습니다.')
#         return redirect(post)
    
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, '포스팅을 삭제했습니다')
#         return redirect('instagram:post_list')

#     return render(request, 'instagram/post_confirm_delete.html', {
#         'post':post,
#     })

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('instagram:post_list')

    # def get_success_url(self):
    #     return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()

# @login_required
# def post_list(request:HttpRequest):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     page = request.GET.get('page', '1')
#     if q:
#         qs = qs.filter(message__icontains=q)
#     paginator = Paginator(qs, 10) # 한 페이지당 10개씩
#     page_obj = paginator.get_page(page)
#     return render(request, 'instagram/post_list.html', {
#         'post_list':page_obj,
#         'q':q,
#     })#

@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    model = Post
    paginate_by = 10

    
post_list = PostListView.as_view()

def post_detail(requset:HttpRequest, pk) -> HttpResponse: 
    # try:
    #     post = Post.objects.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404
    if not requset.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk, is_public=True)
    else:
        post = get_object_or_404(Post, pk=pk)

    return render(requset, 'instagram/post_detail.html', {
        'post':post
    })
# post_detail = DetailView.as_view(model=Post, pk_url_kwarg='pk')

# def archives_year(request:HttpRequest, year) -> HttpResponse:
#     return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

django_instagram_prototype/instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2>date_list</h2>

{% for date in date_list %}
    {{ date.year }}
{% endfor %}

django_instagram_prototype/instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{ year }}

<h2>previous_year</h2>
{{ previous_year }}

<h2>next_year</h2>
{{ next_year }}

<h2>date_list</h2>
{{ date_list }}

<h2>object_list</h2>
{{ object_list }}

django_instagram_prototype/instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        
        <div class="alert alert-danger">
            삭제하시겠습니까?
        </div>
        
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            취소
        </a>
        <input type="submit" value="삭제" class="btn btn-danger">
    </form>
{% endblock content %}

django_instagram_prototype/instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% block title %}
    Post Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}" , style="width: 150px;">
        </div>
    {% endif %}

    {{ post.message|linebreaks }}
    <hr/>
    <a href=" {% url 'instagram:post_list' %}" class="btn btn-primary">
        <span style="color: white;">목록</span>
    </a>
    <a href=" {% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
        <span style="color: white;">수정</span>
    </a>

    <a href=" {% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        <span style="color: white;">삭제</span>
    </a>
{% endblock content %}

django_instagram_prototype/instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- <table>
            {{ form.as_table }}
        </table> -->
        {% buttons %}
        <button class="btn btn-primary">
            저장
        </button>
        {% endbuttons %}
        <!-- <input type="submit" value="저장"> -->
    </form>
    <hr/>
    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}
    <a href=" {% url 'instagram:post_list' %} " class="btn btn-primary">목록</a>
{% endblock content %}

django_instagram_prototype/instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post_list
{% endblock title %}

{% block content %}
    <form action="" method="get">
        <input type="text" , name="q" , value="{{ q }}" />
        <input type="submit" , value="검색" />
    </form>
    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary  w-100 mt-2 mb-2">새 포스팅</a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
            <tr>
                <td>
                    {{ post.id }}
                </td>
                <td>
                    {% if post.photo %}
                    <img src="{{ post.photo.url }}" , style="width: 100px;" />
                    {% else %}
                    No Photo
                    {% endif %}
                </td>
                <td>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.message }}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
    {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}
{% endblock content %}