django_instagram_prototype/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

django_instagram_prototype/django_instagram_prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

class RootView(TemplateView):
    template_name = 'root.html'

urlpatterns = [
    # path('', RootView.as_view(), name='root'), # TemplateView.as_view(template_name='root.html')
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
      urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
      import debug_toolbar
      urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

django_instagram_prototype/django_instagram_prototype/templates/layout.html
{% load bootstrap4 static %}
<!doctype html>
<html lang="ko">

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.css' %}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.js' %}"></script>
    <style>
        body {
            padding-top: 3.8rem;
            padding-bottom: 2rem;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'instagram:post_list' %}">ukstagram</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
                aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' %}">프로필</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>
                {% endif %}


            </ul>
            <form>
                <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <!-- {% bootstrap_messages %} -->
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message.message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            {% block content %}
            {% endblock content %}

            <hr/>
            &copy; Sungwook
        </div>
    </div>
</div>


</body>

</html>

django_instagram_prototype/django_instagram_prototype/templates/root.html
<h2>ukstagram with Django</h2>