django_instagram_prototype/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

django_instagram_prototype/django_instagram_prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

class RootView(TemplateView):
    template_name = 'root.html'

urlpatterns = [
    # path('', RootView.as_view(), name='root'), # TemplateView.as_view(template_name='root.html')
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
      urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
      import debug_toolbar
      urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

django_instagram_prototype/accounts/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, blank=True) # 주소
    zipcode = models.CharField(max_length=6, blank=True) # 우편 번호

django_instagram_prototype/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm

from .models import Profile
from django import forms

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'zipcode']

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(help_text='3 + 3 = ?')

    def clean_answer(self):
        answer = self.cleaned_data.get('answer')
        if answer != 6:
            raise forms.ValidationError('틀렸습니다')
        return answer

django_instagram_prototype/accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, CreateView
from .models import Profile
from .forms import ProfileForm, LoginForm

login = LoginView.as_view(template_name='accounts/login_form.html',
                          form_class=LoginForm)

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def profile_edit(request):
    try:
        profile = request.user.profile # Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_form.html', {
        'form':form,
    })


User = get_user_model()
class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = 'accounts/signup_form.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object
        auth_login(self.request, user)
        return response

signup = SignupView.as_view()


logout = LogoutView.as_view()

django_instagram_prototype/accounts/templates/accounts/layout.html
{% extends "layout.html" %}

django_instagram_prototype/accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap4 %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">로그인</button>
        {% endbuttons %}
    </form>
{% endblock content %}

django_instagram_prototype/accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>User: {{ user }}</h2>

    {% if user.profile %}
        <ul>
            <li>{{ user.profile.address }}</li>
            <li>{{ user.profile.zipcode }}</li>
        </ul>
    {% endif %}

    <a href="{% url 'accounts:profile_edit' %}" class="btn btn-primary"> 프로필 수정 </a>
{% endblock content %}

django_instagram_prototype/accounts/templates/accounts/profile_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap4 %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">프로필 수정</button>
        {% endbuttons %}
    </form>
{% endblock content %}

django_instagram_prototype/accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap4 %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary">회원가입</button>
        {% endbuttons %}
    </form>
{% endblock content %}